### ISSUE TITLE
Mapa mental

### ISSUE THREAD

**Issue by 27Fer12** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-27Fer12#1]
[web 3.0_Fernanda Ruiz Heras.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-27Fer12/files/14662241/web.3.0_Fernanda.Ruiz.Heras.pdf)

**Comment by Nelsy21** [comment]
20/20 calificado conforme a la rubrica.                                                                                    
Buen trabajo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
